"""
Server-side skill/tech extraction from job titles and descriptions.
Mirrors the client-side SKILL_DB patterns so tags are consistent.
"""
import re

# Each entry: (display_name, regex_pattern, category)
SKILL_DB = [
    # Languages
    ("Python", re.compile(r"\bPython\b", re.I), "lang"),
    ("JavaScript", re.compile(r"\bJavaScript\b", re.I), "lang"),
    ("TypeScript", re.compile(r"\bTypeScript\b", re.I), "lang"),
    ("Java", re.compile(r"\bJava\b(?!\s*Script)", re.I), "lang"),
    ("C#", re.compile(r"\bC#|\.NET\b", re.I), "lang"),
    ("C++", re.compile(r"\bC\+\+\b", re.I), "lang"),
    ("Go", re.compile(r"\bGolang\b|\bGo\b(?=\s+(developer|engineer|programming|language))", re.I), "lang"),
    ("Rust", re.compile(r"\bRust\b", re.I), "lang"),
    ("Ruby", re.compile(r"\bRuby\b", re.I), "lang"),
    ("PHP", re.compile(r"\bPHP\b", re.I), "lang"),
    ("Swift", re.compile(r"\bSwift\b", re.I), "lang"),
    ("Kotlin", re.compile(r"\bKotlin\b", re.I), "lang"),
    ("Scala", re.compile(r"\bScala\b", re.I), "lang"),
    ("R", re.compile(r"\bR\b(?=\s+(programming|studio|language|statistical))", re.I), "lang"),
    ("SQL", re.compile(r"\bSQL\b", re.I), "data"),
    # Data & Analytics
    ("Power BI", re.compile(r"\bPower\s*BI\b", re.I), "data"),
    ("Tableau", re.compile(r"\bTableau\b", re.I), "data"),
    ("Excel", re.compile(r"\bExcel\b", re.I), "data"),
    ("Snowflake", re.compile(r"\bSnowflake\b", re.I), "data"),
    ("BigQuery", re.compile(r"\bBigQuery\b", re.I), "data"),
    ("Databricks", re.compile(r"\bDatabricks\b", re.I), "data"),
    ("Spark", re.compile(r"\bApache\s*Spark\b|\bPySpark\b|\bSpark\b", re.I), "data"),
    ("Hadoop", re.compile(r"\bHadoop\b", re.I), "data"),
    ("Kafka", re.compile(r"\bKafka\b", re.I), "data"),
    ("Airflow", re.compile(r"\bAirflow\b", re.I), "data"),
    ("dbt", re.compile(r"\bdbt\b", re.I), "data"),
    ("Looker", re.compile(r"\bLooker\b", re.I), "data"),
    ("Redshift", re.compile(r"\bRedshift\b", re.I), "data"),
    ("PostgreSQL", re.compile(r"\bPostgres(?:QL)?\b", re.I), "data"),
    ("MongoDB", re.compile(r"\bMongoDB?\b", re.I), "data"),
    ("Redis", re.compile(r"\bRedis\b", re.I), "data"),
    ("Elasticsearch", re.compile(r"\bElasticsearch\b|\bElastic\b", re.I), "data"),
    ("MySQL", re.compile(r"\bMySQL\b", re.I), "data"),
    ("Oracle DB", re.compile(r"\bOracle\s*(DB|Database)\b", re.I), "data"),
    ("ETL", re.compile(r"\bETL\b", re.I), "data"),
    # Cloud
    ("AWS", re.compile(r"\bAWS\b|\bAmazon Web Services\b", re.I), "cloud"),
    ("Azure", re.compile(r"\bAzure\b", re.I), "cloud"),
    ("GCP", re.compile(r"\bGCP\b|\bGoogle Cloud\b", re.I), "cloud"),
    ("Salesforce", re.compile(r"\bSalesforce\b|\bSFDC\b", re.I), "cloud"),
    ("SAP", re.compile(r"\bSAP\b", re.I), "cloud"),
    ("ServiceNow", re.compile(r"\bServiceNow\b", re.I), "cloud"),
    # Frameworks
    ("React", re.compile(r"\bReact(?:\.?js|JS)?\b", re.I), "framework"),
    ("Angular", re.compile(r"\bAngular\b", re.I), "framework"),
    ("Vue", re.compile(r"\bVue(?:\.?js)?\b", re.I), "framework"),
    ("Node.js", re.compile(r"\bNode(?:\.?js|JS)\b", re.I), "framework"),
    ("Django", re.compile(r"\bDjango\b", re.I), "framework"),
    ("Flask", re.compile(r"\bFlask\b", re.I), "framework"),
    ("Spring", re.compile(r"\bSpring\s*Boot\b|\bSpring\b", re.I), "framework"),
    ("Rails", re.compile(r"\bRails\b|\bRuby on Rails\b", re.I), "framework"),
    ("Next.js", re.compile(r"\bNext(?:\.?js|JS)\b", re.I), "framework"),
    (".NET", re.compile(r"\b\.NET\s*(?:Core|Framework)?\b", re.I), "framework"),
    ("FastAPI", re.compile(r"\bFastAPI\b", re.I), "framework"),
    ("GraphQL", re.compile(r"\bGraphQL\b", re.I), "framework"),
    ("REST API", re.compile(r"\bREST(?:ful)?\s*API\b", re.I), "framework"),
    # DevOps & Infra
    ("Docker", re.compile(r"\bDocker\b", re.I), "devops"),
    ("Kubernetes", re.compile(r"\bKubernetes\b|\bK8s\b", re.I), "devops"),
    ("Terraform", re.compile(r"\bTerraform\b", re.I), "devops"),
    ("Jenkins", re.compile(r"\bJenkins\b", re.I), "devops"),
    ("CI/CD", re.compile(r"\bCI\s*\/?\s*CD\b", re.I), "devops"),
    ("Linux", re.compile(r"\bLinux\b", re.I), "devops"),
    ("Git", re.compile(r"\bGit\b(?!Hub|Lab)", re.I), "devops"),
    ("GitHub", re.compile(r"\bGitHub\b", re.I), "devops"),
    ("Ansible", re.compile(r"\bAnsible\b", re.I), "devops"),
    ("Prometheus", re.compile(r"\bPrometheus\b", re.I), "devops"),
    ("Grafana", re.compile(r"\bGrafana\b", re.I), "devops"),
    # AI/ML
    ("Machine Learning", re.compile(r"\bMachine Learning\b|\bML\b", re.I), "ai"),
    ("Deep Learning", re.compile(r"\bDeep Learning\b", re.I), "ai"),
    ("TensorFlow", re.compile(r"\bTensorFlow\b", re.I), "ai"),
    ("PyTorch", re.compile(r"\bPyTorch\b", re.I), "ai"),
    ("NLP", re.compile(r"\bNLP\b|\bNatural Language Processing\b", re.I), "ai"),
    ("LLM", re.compile(r"\bLLM\b|\bLarge Language Model\b", re.I), "ai"),
    ("GenAI", re.compile(r"\bGenerative AI\b|\bGenAI\b|\bGen AI\b", re.I), "ai"),
    ("Computer Vision", re.compile(r"\bComputer Vision\b|\bCV\b(?=.*(?:model|image|detect))", re.I), "ai"),
    ("OpenAI", re.compile(r"\bOpenAI\b|\bChatGPT\b|\bGPT[-\s]?4\b", re.I), "ai"),
    ("Hugging Face", re.compile(r"\bHugging\s*Face\b", re.I), "ai"),
    # Tools
    ("Jira", re.compile(r"\bJira\b", re.I), "tool"),
    ("Confluence", re.compile(r"\bConfluence\b", re.I), "tool"),
    ("Figma", re.compile(r"\bFigma\b", re.I), "design"),
    ("Sketch", re.compile(r"\bSketch\b", re.I), "design"),
    ("Adobe XD", re.compile(r"\bAdobe\s*XD\b", re.I), "design"),
    ("Photoshop", re.compile(r"\bPhotoshop\b", re.I), "design"),
    ("Illustrator", re.compile(r"\bIllustrator\b", re.I), "design"),
    ("InDesign", re.compile(r"\bInDesign\b", re.I), "design"),
    ("Canva", re.compile(r"\bCanva\b", re.I), "design"),
    ("HubSpot", re.compile(r"\bHubSpot\b", re.I), "tool"),
    ("Marketo", re.compile(r"\bMarketo\b", re.I), "tool"),
    ("Google Analytics", re.compile(r"\bGoogle Analytics\b|\bGA4\b", re.I), "tool"),
    ("SEO", re.compile(r"\bSEO\b", re.I), "tool"),
    ("SEM", re.compile(r"\bSEM\b|\bGoogle Ads\b", re.I), "tool"),
    ("Zendesk", re.compile(r"\bZendesk\b", re.I), "tool"),
    ("Intercom", re.compile(r"\bIntercom\b", re.I), "tool"),
    # Business
    ("Agile", re.compile(r"\bAgile\b", re.I), "business"),
    ("Scrum", re.compile(r"\bScrum\b", re.I), "business"),
    ("Six Sigma", re.compile(r"\bSix Sigma\b", re.I), "business"),
    ("PMP", re.compile(r"\bPMP\b", re.I), "business"),
    ("CPA", re.compile(r"\bCPA\b", re.I), "business"),
    ("GAAP", re.compile(r"\bGAAP\b", re.I), "business"),
    ("SOC 2", re.compile(r"\bSOC\s*2\b", re.I), "security"),
    ("HIPAA", re.compile(r"\bHIPAA\b", re.I), "security"),
    ("SOX", re.compile(r"\bSOX\b|\bSarbanes", re.I), "security"),
    # Security
    ("Cybersecurity", re.compile(r"\bCyber\s*Security\b|\bCybersecurity\b", re.I), "security"),
    ("SIEM", re.compile(r"\bSIEM\b", re.I), "security"),
    ("Penetration Testing", re.compile(r"\bPen\s*Test\b|\bPenetration Testing\b", re.I), "security"),
    ("CISSP", re.compile(r"\bCISSP\b", re.I), "security"),
    ("CompTIA Security+", re.compile(r"\bSecurity\+\b|\bCompTIA\s*Security", re.I), "security"),
    ("Zero Trust", re.compile(r"\bZero\s*Trust\b", re.I), "security"),
    ("IAM", re.compile(r"\bIAM\b", re.I), "security"),
    ("OWASP", re.compile(r"\bOWASP\b", re.I), "security"),

    # More Languages
    ("Perl", re.compile(r"\bPerl\b", re.I), "lang"),
    ("Lua", re.compile(r"\bLua\b", re.I), "lang"),
    ("Dart", re.compile(r"\bDart\b", re.I), "lang"),
    ("Elixir", re.compile(r"\bElixir\b", re.I), "lang"),
    ("Haskell", re.compile(r"\bHaskell\b", re.I), "lang"),
    ("MATLAB", re.compile(r"\bMATLAB\b", re.I), "lang"),
    ("Shell/Bash", re.compile(r"\bBash\b|\bShell\s*Script", re.I), "lang"),
    ("PowerShell", re.compile(r"\bPowerShell\b", re.I), "lang"),
    ("Solidity", re.compile(r"\bSolidity\b", re.I), "lang"),

    # More Frameworks & Libraries
    ("Express.js", re.compile(r"\bExpress(?:\.?js)?\b", re.I), "framework"),
    ("Svelte", re.compile(r"\bSvelte\b", re.I), "framework"),
    ("Nuxt", re.compile(r"\bNuxt\b", re.I), "framework"),
    ("Remix", re.compile(r"\bRemix\b", re.I), "framework"),
    ("Tailwind", re.compile(r"\bTailwind\b", re.I), "framework"),
    ("Bootstrap", re.compile(r"\bBootstrap\b", re.I), "framework"),
    ("jQuery", re.compile(r"\bjQuery\b", re.I), "framework"),
    ("Flutter", re.compile(r"\bFlutter\b", re.I), "framework"),
    ("React Native", re.compile(r"\bReact\s*Native\b", re.I), "framework"),
    ("Electron", re.compile(r"\bElectron\b", re.I), "framework"),
    ("Unity", re.compile(r"\bUnity\b(?=.*(?:game|3D|engine|developer))", re.I), "framework"),
    ("Unreal", re.compile(r"\bUnreal\s*Engine\b|\bUnreal\b", re.I), "framework"),
    ("Laravel", re.compile(r"\bLaravel\b", re.I), "framework"),
    ("Symfony", re.compile(r"\bSymfony\b", re.I), "framework"),
    ("Celery", re.compile(r"\bCelery\b", re.I), "framework"),
    ("RabbitMQ", re.compile(r"\bRabbitMQ\b", re.I), "data"),
    ("gRPC", re.compile(r"\bgRPC\b", re.I), "framework"),
    ("Microservices", re.compile(r"\bMicroservices?\b", re.I), "framework"),

    # More Data & Databases
    ("DynamoDB", re.compile(r"\bDynamoDB\b", re.I), "data"),
    ("Cassandra", re.compile(r"\bCassandra\b", re.I), "data"),
    ("Neo4j", re.compile(r"\bNeo4j\b", re.I), "data"),
    ("CouchDB", re.compile(r"\bCouchDB\b", re.I), "data"),
    ("Firebase", re.compile(r"\bFirebase\b", re.I), "data"),
    ("Supabase", re.compile(r"\bSupabase\b", re.I), "data"),
    ("Prisma", re.compile(r"\bPrisma\b", re.I), "data"),
    ("SQLAlchemy", re.compile(r"\bSQLAlchemy\b", re.I), "data"),
    ("Pandas", re.compile(r"\bPandas\b", re.I), "data"),
    ("NumPy", re.compile(r"\bNumPy\b", re.I), "data"),
    ("SAS", re.compile(r"\bSAS\b", re.I), "data"),
    ("SPSS", re.compile(r"\bSPSS\b", re.I), "data"),
    ("Data Warehouse", re.compile(r"\bData\s*Warehouse\b|\bData\s*Warehousing\b", re.I), "data"),
    ("Data Pipeline", re.compile(r"\bData\s*Pipeline\b", re.I), "data"),
    ("Data Lake", re.compile(r"\bData\s*Lake\b", re.I), "data"),

    # More Cloud & Infrastructure
    ("Heroku", re.compile(r"\bHeroku\b", re.I), "cloud"),
    ("Vercel", re.compile(r"\bVercel\b", re.I), "cloud"),
    ("Netlify", re.compile(r"\bNetlify\b", re.I), "cloud"),
    ("DigitalOcean", re.compile(r"\bDigitalOcean\b", re.I), "cloud"),
    ("Cloudflare", re.compile(r"\bCloudflare\b", re.I), "cloud"),
    ("Twilio", re.compile(r"\bTwilio\b", re.I), "cloud"),
    ("Stripe", re.compile(r"\bStripe\b", re.I), "cloud"),
    ("Okta", re.compile(r"\bOkta\b", re.I), "cloud"),
    ("Auth0", re.compile(r"\bAuth0\b", re.I), "cloud"),
    ("Snowpark", re.compile(r"\bSnowpark\b", re.I), "cloud"),

    # More DevOps & Infra
    ("ArgoCD", re.compile(r"\bArgo\s*CD\b", re.I), "devops"),
    ("Helm", re.compile(r"\bHelm\b", re.I), "devops"),
    ("Istio", re.compile(r"\bIstio\b", re.I), "devops"),
    ("Nginx", re.compile(r"\bNginx\b", re.I), "devops"),
    ("Apache", re.compile(r"\bApache\b(?!\s*Spark|\s*Kafka|\s*Airflow|\s*Hadoop)", re.I), "devops"),
    ("Datadog", re.compile(r"\bDatadog\b", re.I), "devops"),
    ("Splunk", re.compile(r"\bSplunk\b", re.I), "devops"),
    ("New Relic", re.compile(r"\bNew Relic\b", re.I), "devops"),
    ("PagerDuty", re.compile(r"\bPagerDuty\b", re.I), "devops"),
    ("CloudFormation", re.compile(r"\bCloudFormation\b", re.I), "devops"),
    ("Pulumi", re.compile(r"\bPulumi\b", re.I), "devops"),
    ("Vagrant", re.compile(r"\bVagrant\b", re.I), "devops"),
    ("GitLab", re.compile(r"\bGitLab\b", re.I), "devops"),
    ("Bitbucket", re.compile(r"\bBitbucket\b", re.I), "devops"),
    ("CircleCI", re.compile(r"\bCircleCI\b", re.I), "devops"),
    ("GitHub Actions", re.compile(r"\bGitHub\s*Actions\b", re.I), "devops"),
    ("AWS Lambda", re.compile(r"\bLambda\b", re.I), "cloud"),
    ("Serverless", re.compile(r"\bServerless\b", re.I), "devops"),
    ("ECS", re.compile(r"\bECS\b", re.I), "cloud"),
    ("EKS", re.compile(r"\bEKS\b", re.I), "cloud"),
    ("S3", re.compile(r"\bS3\b", re.I), "cloud"),

    # More AI/ML
    ("Scikit-learn", re.compile(r"\bScikit[\-\s]*learn\b|\bsklearn\b", re.I), "ai"),
    ("XGBoost", re.compile(r"\bXGBoost\b", re.I), "ai"),
    ("LangChain", re.compile(r"\bLangChain\b", re.I), "ai"),
    ("RAG", re.compile(r"\bRAG\b|\bRetrieval[\-\s]*Augmented", re.I), "ai"),
    ("MLOps", re.compile(r"\bMLOps\b", re.I), "ai"),
    ("MLflow", re.compile(r"\bMLflow\b", re.I), "ai"),
    ("SageMaker", re.compile(r"\bSageMaker\b", re.I), "ai"),
    ("Vertex AI", re.compile(r"\bVertex\s*AI\b", re.I), "ai"),
    ("Stable Diffusion", re.compile(r"\bStable\s*Diffusion\b", re.I), "ai"),
    ("BERT", re.compile(r"\bBERT\b", re.I), "ai"),
    ("Transformers", re.compile(r"\bTransformers?\b(?=.*(?:model|NLP|AI|ML))", re.I), "ai"),
    ("Prompt Engineering", re.compile(r"\bPrompt\s*Engineer", re.I), "ai"),
    ("Fine-tuning", re.compile(r"\bFine[\-\s]*tun", re.I), "ai"),
    ("Vector DB", re.compile(r"\bVector\s*(DB|Database)\b|\bPinecone\b|\bWeaviate\b|\bChromaDB\b|\bMilvus\b|\bQdrant\b", re.I), "ai"),
    ("Claude", re.compile(r"\bClaude\b|\bAnthropic\b", re.I), "ai"),

    # Design & Creative
    ("After Effects", re.compile(r"\bAfter\s*Effects\b", re.I), "design"),
    ("Premiere", re.compile(r"\bPremiere\b", re.I), "design"),
    ("Blender", re.compile(r"\bBlender\b", re.I), "design"),
    ("AutoCAD", re.compile(r"\bAutoCAD\b", re.I), "design"),
    ("SolidWorks", re.compile(r"\bSolidWorks\b", re.I), "design"),
    ("UI/UX", re.compile(r"\bUI\s*\/?\s*UX\b|\bUX\s*\/?\s*UI\b|\bUser Experience\b|\bUser Interface\b", re.I), "design"),
    ("Wireframing", re.compile(r"\bWireframe?\b|\bWireframing\b", re.I), "design"),
    ("Prototyping", re.compile(r"\bPrototyp", re.I), "design"),

    # Project Management & Business Tools
    ("Monday.com", re.compile(r"\bMonday\.com\b|\bMonday\b(?=.*(?:project|board|tool))", re.I), "tool"),
    ("Asana", re.compile(r"\bAsana\b", re.I), "tool"),
    ("Trello", re.compile(r"\bTrello\b", re.I), "tool"),
    ("Notion", re.compile(r"\bNotion\b", re.I), "tool"),
    ("Slack", re.compile(r"\bSlack\b", re.I), "tool"),
    ("Teams", re.compile(r"\bMicrosoft\s*Teams\b|\bMS\s*Teams\b", re.I), "tool"),
    ("Zoom", re.compile(r"\bZoom\b", re.I), "tool"),
    ("Airtable", re.compile(r"\bAirtable\b", re.I), "tool"),
    ("Zapier", re.compile(r"\bZapier\b", re.I), "tool"),
    ("Snowflake Admin", re.compile(r"\bSnowflake\s*Admin", re.I), "tool"),
    ("Segment", re.compile(r"\bSegment\b", re.I), "tool"),
    ("Amplitude", re.compile(r"\bAmplitude\b", re.I), "tool"),
    ("Mixpanel", re.compile(r"\bMixpanel\b", re.I), "tool"),
    ("Heap", re.compile(r"\bHeap\b(?=.*(?:analytics|tracking))", re.I), "tool"),
    ("Pendo", re.compile(r"\bPendo\b", re.I), "tool"),
    ("Braze", re.compile(r"\bBraze\b", re.I), "tool"),
    ("Mailchimp", re.compile(r"\bMailchimp\b", re.I), "tool"),
    ("SendGrid", re.compile(r"\bSendGrid\b", re.I), "tool"),

    # Certifications & Standards
    ("AWS Certified", re.compile(r"\bAWS\s*Certif", re.I), "business"),
    ("Azure Certified", re.compile(r"\bAzure\s*Certif", re.I), "business"),
    ("GCP Certified", re.compile(r"\bGCP\s*Certif|\bGoogle\s*Cloud\s*Certif", re.I), "business"),
    ("ITIL", re.compile(r"\bITIL\b", re.I), "business"),
    ("Lean", re.compile(r"\bLean\b(?=\s+(Six|manufact|methodol|process))", re.I), "business"),
    ("Kanban", re.compile(r"\bKanban\b", re.I), "business"),
    ("TOGAF", re.compile(r"\bTOGAF\b", re.I), "business"),
    ("COBIT", re.compile(r"\bCOBIT\b", re.I), "business"),
    ("ISO 27001", re.compile(r"\bISO\s*27001\b", re.I), "security"),
    ("GDPR", re.compile(r"\bGDPR\b", re.I), "security"),
    ("CCPA", re.compile(r"\bCCPA\b", re.I), "security"),
    ("PCI DSS", re.compile(r"\bPCI[\-\s]*DSS\b|\bPCI\s*Compliance\b", re.I), "security"),
    ("FedRAMP", re.compile(r"\bFedRAMP\b", re.I), "security"),
    ("NIST", re.compile(r"\bNIST\b", re.I), "security"),

    # ERP & Enterprise
    ("Oracle", re.compile(r"\bOracle\b(?!\s*(DB|Database))", re.I), "cloud"),
    ("NetSuite", re.compile(r"\bNetSuite\b", re.I), "cloud"),
    ("Workday HR", re.compile(r"\bWorkday\b", re.I), "cloud"),
    ("Dynamics 365", re.compile(r"\bDynamics\s*365\b", re.I), "cloud"),
    ("Shopify", re.compile(r"\bShopify\b", re.I), "cloud"),
    ("Magento", re.compile(r"\bMagento\b", re.I), "cloud"),
    ("WordPress", re.compile(r"\bWordPress\b", re.I), "tool"),
    ("Drupal", re.compile(r"\bDrupal\b", re.I), "tool"),

    # Testing & QA
    ("Selenium", re.compile(r"\bSelenium\b", re.I), "tool"),
    ("Cypress", re.compile(r"\bCypress\b", re.I), "tool"),
    ("Playwright", re.compile(r"\bPlaywright\b", re.I), "tool"),
    ("Jest", re.compile(r"\bJest\b", re.I), "tool"),
    ("PyTest", re.compile(r"\bPyTest\b|\bpy\.test\b", re.I), "tool"),
    ("JUnit", re.compile(r"\bJUnit\b", re.I), "tool"),
    ("Postman", re.compile(r"\bPostman\b", re.I), "tool"),
    ("Load Testing", re.compile(r"\bLoad\s*Test|\bPerformance\s*Test|\bJMeter\b", re.I), "tool"),
    ("A/B Testing", re.compile(r"\bA\s*\/?\s*B\s*Test", re.I), "tool"),

    # Networking & Infrastructure
    ("TCP/IP", re.compile(r"\bTCP\s*\/?\s*IP\b", re.I), "devops"),
    ("DNS", re.compile(r"\bDNS\b", re.I), "devops"),
    ("VPN", re.compile(r"\bVPN\b", re.I), "devops"),
    ("Load Balancer", re.compile(r"\bLoad\s*Balanc", re.I), "devops"),
    ("CDN", re.compile(r"\bCDN\b", re.I), "devops"),
    ("VMware", re.compile(r"\bVMware\b", re.I), "devops"),
    ("Active Directory", re.compile(r"\bActive\s*Directory\b|\bAD\b(?=.*(?:admin|domain|user))", re.I), "devops"),

    # Blockchain & Web3
    ("Blockchain", re.compile(r"\bBlockchain\b", re.I), "lang"),
    ("Ethereum", re.compile(r"\bEthereum\b", re.I), "lang"),
    ("Smart Contracts", re.compile(r"\bSmart\s*Contract", re.I), "lang"),
    ("Web3", re.compile(r"\bWeb3\b|\bWeb\s*3\.0\b", re.I), "lang"),
    ("DeFi", re.compile(r"\bDeFi\b", re.I), "lang"),
    ("NFT", re.compile(r"\bNFT\b", re.I), "lang"),
]


def extract_skills(title: str, description: str) -> str:
    """
    Extract skill/tech tags from job title + description.
    Returns comma-separated skill names (e.g. "Python,AWS,Docker").
    """
    text = f"{title or ''} {description or ''}"
    if not text.strip():
        return ""

    found = []
    seen = set()
    for name, pattern, _cat in SKILL_DB:
        if name not in seen and pattern.search(text):
            seen.add(name)
            found.append(name)
    return ",".join(found)
